{{ if .Values.argorollouts.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "service.fullname" . }}
  labels:
  {{- include "service.labels" . | nindent 4 }}
  {{- if .Values.datadog.enabled }}
    {{- include "datadog.labels" . | nindent 4 }}
  {{- end }}
  {{- with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.deploymentAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    canary:
      {{- if .Values.argorollouts.analysis }}
      analysis:
        {{- toYaml .Values.argorollouts.analysis | nindent 8}}
      {{- end }}
      canaryService: {{ include "service.fullname" . }}-service-canary
      stableService: {{ include "service.fullname" . }}-service
      stableMetadata:
        labels:
          app.kubernetes.io/part-of: stable
          role: stable
      canaryMetadata:
        labels:
          app.kubernetes.io/part-of: canary
          role: canary
      trafficRouting:
        nginx:
          stableIngress: {{ include "service.fullname" . }}-ingress
      steps:
      {{- with .Values.argorollouts.steps }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.vaultAgent.enabled }}
        {{- toYaml .Values.vaultAgent.annotations | nindent 8 }}
      {{- end }}
      {{- if .Values.goreplay.enabled }}
        gke-gcsfuse/volumes: "true"
      {{- end }}
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
        {{- if .Values.datadog.enabled }}
          {{- include "datadog.labels" . | nindent 8 }}
        {{- end }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      affinity:
        {{- with .Values.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelectorLabels }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.vaultAgent.enabled }}
      serviceAccountName: {{ .Values.vaultAgent.serviceAccount }}
      {{- else }}
      serviceAccountName: {{ include "service.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8}}
      {{- end }}
      {{- if .Values.goreplay.enabled }}
      - name: goreplay-traffic
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: {{ .Values.goreplay.gcpbucketName }}
            mountOptions: "implicit-dirs"
            gcsfuseLoggingSeverity: warning
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 6}}
      {{- end }}
      tolerations:
      {{- if .Values.nodeTolerations }}
        {{- toYaml .Values.nodeTolerations | nindent 8}}
      {{- end }}
      containers:
      - name: {{ include "service.name" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
      {{- if .Values.gracePeriod }}
        terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
      {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
        {{- with .Values.livenessProbe }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
        readinessProbe:
        {{- with .Values.readinessProbe }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
        startupProbe:
        {{- with .Values.startupProbe }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
        env: 
        {{- if .Values.containerEnv }}
{{ (tpl ( toYaml .Values.containerEnv) .) | indent 12 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.volumeMounts }}
          {{- toYaml .Values.volumeMounts | nindent 12}}
        {{- end }}
      {{- if .Values.goreplay.enabled }}
      - name: goreplay
        image: {{ .Values.goreplay.image }}
        command: ["./gor"]
        args: {{ toYaml .Values.goreplay.args | nindent 12 }}
        volumeMounts:
        - name: goreplay-traffic
          mountPath: /traffic
      {{- end }}
      {{- if .Values.sidecars }}
        {{- toYaml .Values.sidecars | nindent 6}}
      {{- end }}
---
{{ end }}

