{{- if .Values.entrypointOverride.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "centralized-helm-chart.fullname" . }}-scripts
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -e
{{ (tpl ( .Values.entrypointOverride.script) .) | indent 4 }}
    exec "$@"
{{- end }}