apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-service
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.ports }}
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.extraService.enabled }}
    - port: {{ .Values.extraService.port }}
      targetPort: {{ .Values.extraService.targetPort }}
      protocol: TCP
      name: {{ .Values.extraService.portName }}
    {{- end }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}