{{ if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "service.fullname" . }}-virtualService
spec:
  hosts:
    {{- range .Values.virtualService.hosts }}
    - {{ . | quote }}
    {{- end }}
  {{- with .Values.virtualService.http }}
  http:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{ end }}
