{{- $baseConfig := .Files.Get "rudder-config.yaml" | fromYaml -}}
{{- $mergedConfig := mustMergeOverwrite $baseConfig .Values.backend.config.overrides -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rudderstack.fullname" . }}-config
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWaves.prereqs | quote }}
data:
  config.yaml: |-
    {{ $mergedConfig | toYaml | nindent 4 }}
  {{- if .Values.backend.controlPlaneJSON }}
  workspaceConfig.json: |-
{{ .Files.Get "workspaceConfig.json" | indent 4 }}
  {{- end }}
