{{- if .Values.backend.gateway.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
    {{- include "rudderstack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWaves.gateway | quote }}
spec:
  maxUnavailable: {{ .Values.backend.gateway.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
{{- end }}
