name: Chart Release

on:
  push:
    branches: [ master ]
    paths:
    - 'charts/cron-jobs/**'
    - 'charts/service/**'
    - 'scripts/helm-release-chart.sh'
    - '.github/workflows/chart-release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Release chart
        shell: bash
        run: bash scripts/helm-release-chart.sh