name: Helm docs
on: [pull_request]
jobs:
  lint-changelog:
    name: Check all docs
    runs-on: ubuntu-latest
    container:
      image: jnorwood/helm-docs:v1.11.0
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Check README.md
      run: |
        sh scripts/helm-docs.sh
