name: 'Release Drafter'
on:
  push:
    branches:
      - main
    # paths:
    # - 'service/**'
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: release-drafter/release-drafter@v5
