name: 'Release Drafter'
on:
  push:
    branches:
      - main
    paths:
    - 'service/**'
jobs:
  update_release_draft:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - uses: release-drafter/release-drafter@v5

