name: 'release-drafter'

on:
  push:
    tags:
      - "v*" # Run on every commit tag which begins with "v" like (v0.1.3)
    paths:
    - 'service/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
